perso:
    path: /character/{id}
    controller: App\Controller\PersoControleur::character
    requirements:
        id: \d+

accueil:
    path: /hello/{prenom}
    controller: App\Controller\Accueil::bienvenue
    requirements:
        nom: "[a-zA-Z]+"

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }